./setup.sh
Setting up Accessible Tea Timer...
./setup.sh: line 8: [Desktop: command not found
./setup.sh: line 10: Tea: command not found
./setup.sh: line 11: tea: command not found
/home/maradona/GitHub/teatime-accessibility/bin/teatime.py:113: DeprecationWarning: Gtk.Widget.override_font is deprecated
  self.duration_spin.override_font(Pango.FontDescription("Sans Bold 24"))
Traceback (most recent call last):
  File "/home/pele/GitHub/teatime-accessibility/bin/teatime.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
./setup.sh: line 20: EOF: command not found


----

bash ./setup.sh
Setting up Accessible Tea Timer...
Activating virtual environment and installing 'playsound'...
Collecting playsound
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "/home/exoplanetfun/GitHub/teatime-accessibility/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/exoplanetfun/GitHub/teatime-accessibility/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/exoplanetfun/GitHub/teatime-accessibility/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4yn02kfz/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4yn02kfz/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4yn02kfz/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4yn02kfz/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 6, in <module>
        File "/usr/lib/python3.13/inspect.py", line 1258, in getsource
          lines, lnum = getsourcelines(object)
                        ~~~~~~~~~~~~~~^^^^^^^^
        File "/usr/lib/python3.13/inspect.py", line 1240, in getsourcelines
          lines, lnum = findsource(object)
                        ~~~~~~~~~~^^^^^^^^
        File "/usr/lib/python3.13/inspect.py", line 1080, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely ada
